version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: magneto_db
    environment:
      MYSQL_ROOT_PASSWORD: johan
      MYSQL_DATABASE: magneto
      MYSQL_USER: johanmendez
      MYSQL_PASSWORD: meli
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magneto_app
    environment:
      DATABASE_URL: "mysql+pymysql://johanmendez:meli@db:3306/magneto"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
